// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const { describe, it, beforeEach, afterEach } = require('mocha')

describe('test_suite', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('register_user', async function() {
    await driver.get("http://localhost:3000//")
    await driver.manage().window().setRect({ width: 1536, height: 816 })
    await driver.findElement(By.id("get-started-btn")).click()
    await driver.findElement(By.id("input-email-for-credentials-provider")).click()
    await driver.findElement(By.id("input-email-for-credentials-provider")).sendKeys("selenium@example.com")
    await driver.findElement(By.id("input-password-for-credentials-provider")).sendKeys("1234")
    await driver.findElement(By.id("input-new-for-credentials-provider")).click()
    await driver.findElement(By.css("button")).click()
  })
  it('create_post', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    await driver.findElement(By.id("menu-button-4")).click()
    await driver.findElement(By.linkText("Create Post")).click()
    {
      const element = await driver.findElement(By.css(".chakra-editable__preview"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".chakra-editable__input"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".chakra-editable__preview")).click()
    await driver.findElement(By.css(".chakra-editable__input")).sendKeys("Selenium post title")
    await driver.findElement(By.css(".placeholder")).click()
    {
      const element = await driver.findElement(By.css(".ProseMirror"))
      await driver.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p class=\"\">Selenium post content</p>'}", element)
    }
    await driver.findElement(By.xpath("//button[@type=\'submit\']")).click()
  })
  it('create_post_missing_fields', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    await driver.findElement(By.id("menu-button-4")).click()
    await driver.findElement(By.linkText("Create Post")).click()
    await driver.findElement(By.xpath("//button[@type=\'submit\']")).click()
    {
      const elements = await driver.findElements(By.xpath("//div[contains(.,\'Missing fields\')]"))
      assert(elements.length)
    }
  })
  it('delete_post', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    await driver.findElement(By.xpath("//div[starts-with(@id, \'selenium\')]")).click()
    await driver.findElement(By.id("delete-btn")).click()
  })
  it('edit_post', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    await driver.findElement(By.xpath("//div[starts-with(@id, \'selenium\')]")).click()
    await driver.findElement(By.css(".ProseMirror > p")).click()
    vars["postContent"] = await driver.executeScript("return new Date().toString()")
    {
      const element = await driver.findElement(By.css(".ProseMirror"))
      await driver.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = 'vars["postContent"]'}", element)
    }
    await driver.findElement(By.css(".css-taj3dd")).click()
  })
  it('logout', async function() {
    await driver.get("http://localhost:3000//")
    await driver.findElement(By.id("menu-button-4")).click()
    await driver.findElement(By.id("menu-list-4-menuitem-8")).click()
  })
  it('login_user_missing', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    await driver.findElement(By.id("get-started-btn")).click()
    await driver.findElement(By.css("button")).click()
    {
      const elements = await driver.findElements(By.xpath("//p[contains(.,\'Sign in failed. Check the details you provided are correct.\')]"))
      assert(elements.length)
    }
  })
  it('login_user_invalid', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    await driver.findElement(By.id("get-started-btn")).click()
    await driver.findElement(By.id("input-email-for-credentials-provider")).click()
    await driver.findElement(By.id("input-email-for-credentials-provider")).sendKeys("selenium@example.com")
    await driver.findElement(By.id("input-password-for-credentials-provider")).sendKeys("12345")
    await driver.findElement(By.css("button")).click()
    {
      const elements = await driver.findElements(By.xpath("//p[contains(.,\'Sign in failed. Check the details you provided are correct.\')]"))
      assert(elements.length)
    }
  })
  it('login_user', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    await driver.findElement(By.id("get-started-btn")).click()
    await driver.findElement(By.id("input-email-for-credentials-provider")).click()
    await driver.findElement(By.id("input-email-for-credentials-provider")).sendKeys("selenium@example.com")
    await driver.findElement(By.id("input-password-for-credentials-provider")).sendKeys("1234")
    await driver.findElement(By.css("button")).click()
  })
  it('register_user_exists', async function() {
    await driver.get("http://localhost:3000//")
    await driver.manage().window().setRect({ width: 1536, height: 816 })
    await driver.findElement(By.id("get-started-btn")).click()
    await driver.findElement(By.id("input-email-for-credentials-provider")).click()
    await driver.findElement(By.id("input-email-for-credentials-provider")).sendKeys("selenium@example.com")
    await driver.findElement(By.id("input-password-for-credentials-provider")).sendKeys("1234")
    await driver.findElement(By.id("input-new-for-credentials-provider")).click()
    await driver.findElement(By.css("button")).click()
    {
      const elements = await driver.findElements(By.xpath("//p[contains(.,\'Sign in failed. Check the details you provided are correct.\')]"))
      assert(elements.length)
    }
  })
})
